[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/usagers/personnes-agees/"
to = "/publics/personnes-agees/"

[[redirects]]
from = "/geographie/rural/"
to = "/milieu/rural/"

[[redirects]]
from = "/agenda/2025/12/"
to = "/decouvrir-lecosysteme/agenda/2025/12/"

[[redirects]]
from = "/equipe/romane-clement/"
to = "/decouvrir-lecosysteme/equipe/romane-clement/"

[[redirects]]
from = "/usagers/enfants-et-jeunes/"
to = "/publics/enfants-et-jeunes/"

[[redirects]]
from = "/ressources/indicateurs/innovation-dans-les-usages/"
to = "/ressources/indicateurs/innovation-dinteret-general/innovation-dans-les-usages/"

[[redirects]]
from = "/activite/"
to = "/modalites/"

[[redirects]]
from = "/autonomie-administrative/"
to = "/autonomie-administrative-aa/"

[[redirects]]
from = "/usagers/parentalite/"
to = "/publics/parentalite/"

[[redirects]]
from = "/publics/autonomie-numerique-faible/"
to = "/autonomie-numerique-an/an-faible/"

[[redirects]]
from = "/ressources/les-methodes/audit/"
to = "/ressources/les-methodes/les-outils-de-mise-en-oeuvre/audit/"

[[redirects]]
from = "/ressources/indicateurs/innovation-dans-les-usages/nombre-de-nouveaux-usages-ou-parcours-crees-et-integres-dans-le-service/"
to = "/ressources/indicateurs/innovation-dinteret-general/innovation-dans-les-usages/nombre-de-nouveaux-usages-ou-parcours-crees-et-integres-dans-le-service/"

[[redirects]]
from = "/geographie/"
to = "/milieu/"

[[redirects]]
from = "/audit/"
to = "/ressources/les-methodes/les-outils-de-mise-en-oeuvre/audit/"

[[redirects]]
from = "/ressources/les-methodes/atelier-retex/"
to = "/ressources/les-methodes/les-outils-de-mise-en-oeuvre/atelier-retex/"

[[redirects]]
from = "/usagers/autonomie-administrative-faible/"
to = "/autonomie-administrative-aa/aa-faible/"

[[redirects]]
from = "/usagers/tout-type-de-revenus/"
to = "/publics/tout-type-de-revenus/"

[[redirects]]
from = "/structure/mairie/"
to = "/structures/mairie/"

[[redirects]]
from = "/ressources/indicateurs/usages-et-utilisations-du-service-par-lagent/perception-subjective/"
to = "/ressources/indicateurs/utilite/perception-subjective/"

[[redirects]]
from = "/structures/antenne-france-services/"
to = "/structures/antenne/"

[[redirects]]
from = "/activite/hybride-presentiel-et-en-ligne/"
to = "/modalites/hybride-presentiel-et-en-ligne/"

[[redirects]]
from = "/autonomie-administrative-aa/autonomie-administrative-faible/"
to = "/autonomie-administrative-aa/aa-faible/"

[[redirects]]
from = "/ressources/indicateurs/nombre-de-nouveaux-usages-ou-parcours-crees-et-integres-dans-le-service/"
to = "/ressources/indicateurs/innovation-dinteret-general/innovation-dans-les-usages/nombre-de-nouveaux-usages-ou-parcours-crees-et-integres-dans-le-service/"

[[redirects]]
from = "/adequation-avec-les-objectifs-de-politiques-publiques/"
to = "/familles-dindicateurs/adequation-avec-les-objectifs-de-politiques-publiques/"

[[redirects]]
from = "/usagers/revenus-modestes-a-tres-modestes/"
to = "/publics/revenus-modestes-a-tres-modestes/"

[[redirects]]
from = "/activite/presentiel/"
to = "/modalites/presentiel/"

[[redirects]]
from = "/ressources/indicateurs/usages-et-utilisations-du-service-par-lagent/"
to = "/ressources/indicateurs/utilite/"

[[redirects]]
from = "/equipe/florian-guillanton/"
to = "/decouvrir-lecosysteme/equipe/florian-guillanton/"

[[redirects]]
from = "/demarches/aide-sociale-a-lenfance-ase/france-services-actualisation-rsa-2/"
to = "/demarches/aide-sociale-a-lenfance-ase/ase-prevention-1/"

[[redirects]]
from = "/structure/prefecture/"
to = "/structures/prefecture/"

[[redirects]]
from = "/demarches/demarches-1/"
to = "/demarches-1/"

[[redirects]]
from = "/structure/maison-france-services/"
to = "/structures/fixe/"

[[redirects]]
from = "/publics-precaires-et-eloignes-des-services-publics/"
to = "/publics/publics-precaires-et-eloignes-des-services-publics/"

[[redirects]]
from = "/autonomie-numerique-an/autonomie-numerique-faible/"
to = "/autonomie-numerique-an/an-faible/"

[[redirects]]
from = "/usagers/proprietaires-occupants/"
to = "/publics/proprietaires-occupants/"

[[redirects]]
from = "/activite/avec-rdv/"
to = "/modalites/avec-rdv/"

[[redirects]]
from = "/atelier-retex/"
to = "/ressources/les-methodes/les-outils-de-mise-en-oeuvre/atelier-retex/"

[[redirects]]
from = "/activite/sans-rdv/"
to = "/modalites/sans-rdv/"

[[redirects]]
from = "/agenda/2025/cycle-territoires-et-mobilites-2025-de-lihedate/"
to = "/decouvrir-lecosysteme/agenda/2025/cycle-territoires-et-mobilites-2025-de-lihedate/"

[[redirects]]
from = "/indicateurs/"
to = "/ressources/indicateurs/"

[[redirects]]
from = "/usagers/proprietaires-bailleurs/"
to = "/publics/proprietaires-bailleurs/"

[[redirects]]
from = "/autonomie-administrative-faible/"
to = "/autonomie-administrative-aa/aa-faible/"

[[redirects]]
from = "/agenda/2025/"
to = "/decouvrir-lecosysteme/agenda/2025/"

[[redirects]]
from = "/usagers/autonomie-numerique-faible/"
to = "/autonomie-numerique-an/an-faible/"

[[redirects]]
from = "/publics/autonomie-administrative-faible/"
to = "/autonomie-administrative-aa/aa-faible/"

[[redirects]]
from = "/actualites/2022/10/11/lancement-du-lab/"
to = "/decouvrir-lecosysteme/actualites/2022-10-11-lancement-du-lab/"

[[redirects]]
from = "/structure/ccas/"
to = "/structures/ccas/"

[[redirects]]
from = "/structure/"
to = "/structures/"

[[redirects]]
from = "/structure/la-poste/"
to = "/structures/bureau-de-poste/"

[[redirects]]
from = "/usagers/"
to = "/autonomie-administrative-aa/"

[[redirects]]
from = "/agenda/"
to = "/decouvrir-lecosysteme/agenda/"

[[redirects]]
from = "/agenda/2025/03/"
to = "/decouvrir-lecosysteme/agenda/2025/03/"

[[redirects]]
from = "/aa-moyenne/"
to = "/autonomie-administrative-aa/aa-moyenne/"

[[redirects]]
from = "/structure/bureau-de-poste/"
to = "/structures/bureau-de-poste/"

[[redirects]]
from = "/usagers/professionnels/"
to = "/publics/professionnels/"

[[redirects]]
from = "/usagers/situation-de-handicap-ou-perte-dautonomie/"
to = "/publics/situation-de-handicap-ou-perte-dautonomie/"

[[redirects]]
from = "/activite/sans-mediation/"
to = "/modalites/sans-mediation/"

[[redirects]]
from = "/structure/association/"
to = "/structures/association/"

[[redirects]]
from = "/vehicule/"
to = "/structures/vehicule/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/decouvrir-lecosysteme/equipe/equipe-editoriale/"

[[redirects]]
from = "/actualites/"
to = "/decouvrir-lecosysteme/actualites/"

[[redirects]]
from = "/structures/bus-france-services/"
to = "/structures/vehicule/"

[[redirects]]
from = "/bus-france-services/"
to = "/structures/vehicule/"

[[redirects]]
from = "/structures/france-services-multisites/"
to = "/structures/multisites/"

[[redirects]]
from = "/actualites/2022-10-11-lancement-du-lab/"
to = "/decouvrir-lecosysteme/actualites/2022-10-11-lancement-du-lab/"

[[redirects]]
from = "/organisations/"
to = "/decouvrir-lecosysteme/organisations/"

[[redirects]]
from = "/activite/avec-mediation/"
to = "/modalites/avec-mediation/"

[[redirects]]
from = "/structures/france-services-itinerante/"
to = "/structures/itinerante/"

[[redirects]]
from = "/structures/france-services-fixe/"
to = "/structures/fixe/"

[[redirects]]
from = "/activites/"
to = "/modalites/"

[[redirects]]
from = "/activite/en-ligne/"
to = "/modalites/en-ligne/"

[[redirects]]
from = "/autonomie-administrative/autonomie-numerique-faible/"
to = "/autonomie-numerique-an/an-faible/"

[[redirects]]
from = "/formations/"
to = "/ressources/formations/"

[[redirects]]
from = "/connaitre-les-enjeux/deploiement-de-lia-dans-les-territoires-et-collectivites/"
to = "/connaitre-les-enjeux/technologies/deploiement-de-lia-dans-les-territoires-et-collectivites/"

[[redirects]]
from = "/equipe/"
to = "/decouvrir-lecosysteme/equipe/"

[[redirects]]
from = "/usagers/publics-precaires-et-eloignes-des-services-publics/"
to = "/publics/publics-precaires-et-eloignes-des-services-publics/"

